name: gurps_dart
description: Common code for most GURPS utilities
author: M. Jeff Wilson <geek.macbeer@gmail.com>
homepage: http://hypermediocrity.us
version: 1.3.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  math_expressions: ^2.0.0

dev_dependencies:
  test: ^1.15.1
  build_runner: 
  build_test: 
  test_coverage: 
  json_serializable: ^3.3.0

dependency_overrides:

