name: gurps_dart
description: Common code for most GURPS utilities
author: M. Jeff Wilson <geek.macbeer@gmail.com>
homepage: http://hypermediocrity.us
version: 0.0.1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  test: ^1.5.1+1
  build_runner: ^1.1.2
  build_test: ^0.10.4
  test_coverage: ^0.2.3
  json_serializable: ^2.0.1

dependency_overrides:

